const modalStyle = {
    authenticationBox : {
        width : 400,
        height : 400,
        bgcolor : 'white',
        border : "1px solid #707070",
        p : 2,
        px : 4,
        pb : 3,
        paddingTop : '2rem',
        display : 'flex',
        flexDirection : 'column',
        alignItems : 'center',
    },
    registerBox : {
        width : 400,
        height : 600,
        bgcolor : 'white',
        border : "1px solid #707070",
        p : 2,
        px : 4,
        pb : 3,
        paddingTop : '2rem',
        display : 'flex',
        flexDirection : 'column',
        alignItems : 'center',
    },
    firstBox : {
        width : 400,
        height : 500,
        bgcolor : 'white',
        p : 2,
        px : 4,
        pb : 3,
        paddingTop : '2rem',
        display : 'flex',
        flexDirection : 'column',
        alignItems : 'center',
    },
    secondBox : {
        width : 400,
        height : 400,
        bgcolor : 'white',
        p : 2,
        px : 4,
        pb : 3,
        paddingTop : '1rem',
        display : 'flex',
        flexDirection : 'column',
        alignItems : 'center',
    },
    forgetPasswordBox : {
        width : 300,
        height : 200,
        bgcolor : 'white',
        border : "1px solid #707070",
        p : 2,
        px : 4,
        pb : 3,
        paddingTop : '2rem',
        display : 'flex',
        flexDirection : 'column',
        alignItems : 'center',
    },
    h1 : {
        fontSize : '1.5rem',
        fontWeight : 'bold',
        textAlign : 'center',
        float : 'left',
    },
    formControl : {
        marginTop : '1em',
        width : '30ch',
    },
    formControlForgetPassword : {
        marginTop : '3em',
        width : '175px',
    },
    buttonForm : {
        width : '30ch',
        margin : '0 auto',
        marginTop: '0em',
        display : 'flex',
        flexDirection : 'column',
        alignItems : 'center',
    },
    buttonSwap : {
        width : '30ch',
        margin : '0 auto',
        marginTop: '1rem',
        marginLeft : 50 + '%',
        display : 'flex',
        alignItems : 'center',
    },
    buttonPhase : {
        marginTop : '-2rem',
        display: "flex", 
        flexDirection: "row", pt: 2 
    }
};

export default modalStyle;